(module
  ;; generated by nagiscript (NGS-IR -> WAT)
  ;; runtime functions must be provided by the host via env imports
  (import "env" "__ngs_print_str" (func $__ngs_print_str (param i32) (param i32)))
  (import "env" "__ngs_println_str" (func $__ngs_println_str (param i32) (param i32)))
  (import "env" "__ngs_print_i64" (func $__ngs_print_i64 (param i64)))
  (import "env" "__ngs_println_i64" (func $__ngs_println_i64 (param i64)))
  (import "env" "__ngs_print_f64" (func $__ngs_print_f64 (param f64)))
  (import "env" "__ngs_println_f64" (func $__ngs_println_f64 (param f64)))
  (import "env" "__ngs_print_bool" (func $__ngs_print_bool (param i32)))
  (import "env" "__ngs_println_bool" (func $__ngs_println_bool (param i32)))
  (import "env" "__ngs_panic" (func $__ngs_panic (param i32) (param i32)))
  (import "env" "__ngs_abort" (func $__ngs_abort ))
  (import "env" "__ngs_str_eq" (func $__ngs_str_eq (param i32) (param i32) (result i32)))
  (import "env" "__ngs_str_to_i64" (func $__ngs_str_to_i64 (param i32) (result i64)))
  (import "env" "__ngs_str_to_f64" (func $__ngs_str_to_f64 (param i32) (result f64)))
  (import "env" "__ngs_box_i64" (func $__ngs_box_i64 (param i64) (result i64)))
  (import "env" "__ngs_box_f64" (func $__ngs_box_f64 (param f64) (result i64)))
  (import "env" "__ngs_box_bool" (func $__ngs_box_bool (param i32) (result i64)))
  (import "env" "__ngs_box_str" (func $__ngs_box_str (param i32) (result i64)))
  (import "env" "__ngs_box_ptr" (func $__ngs_box_ptr (param i32) (result i64)))
  (import "env" "__ngs_props_new" (func $__ngs_props_new  (result i32)))
  (import "env" "__ngs_props_tag" (func $__ngs_props_tag (param i32) (param i32) (param i32)))
  (import "env" "__ngs_props_set" (func $__ngs_props_set (param i32) (param i32) (param i32) (param i64)))
  (import "env" "__ngs_props_add_child" (func $__ngs_props_add_child (param i32) (param i64)))
  (import "env" "__ngs_fmod" (func $__ngs_fmod (param f64) (param f64) (result f64)))
  (memory (export "memory") 2)
  (global $heap (mut i32) (i32.const 288))
  (data (i32.const 0) "\3d\3d\3d\20\4e\61\67\69\53\63\72\69\70\74\20\50\6c\61\79\67\72\6f\75\6e\64\20\3d\3d\3d\00\00\00\00\00\00\00\00\00\00\00\1d\00\00\00\00\00\00\00\57\41\53\4d\20\6d\6f\64\75\6c\65\20\6c\6f\61\64\65\64\20\73\75\63\63\65\73\73\66\75\6c\6c\79\21\30\00\00\00\00\00\00\00\20\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\60\00\00\00\00\00\00\00\10\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\80\00\00\00\00\00\00\00\10\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\a0\00\00\00\00\00\00\00\10\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\c0\00\00\00\00\00\00\00\10\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\e0\00\00\00\00\00\00\00\10\00\00\00\00\00\00\00\69\6e\74\65\67\65\72\20\6f\76\65\72\66\6c\6f\77\00\01\00\00\00\00\00\00\10\00\00\00\00\00\00\00")
(func $main (local i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32) (local i64) (local i32 i32 i32) (local i64)
  global.get $heap
  local.set 10
  loop $top
    block $next
      local.get 11
      i32.eqz
      if
        ;; block entry (pc=0)
        i32.const 32
        local.set 0
        local.get 0
        i32.const 0
        i32.add
        local.set 1
        local.get 0
        i32.const 8
        i32.add
        local.set 2
        local.get 1
        i32.load
        local.set 3
        local.get 2
        i64.load
        local.set 4
        local.get 3
        local.get 4
        i32.wrap_i64
        call $__ngs_print_str
        i32.const 80
        local.set 5
        local.get 5
        i32.const 0
        i32.add
        local.set 6
        local.get 5
        i32.const 8
        i32.add
        local.set 7
        local.get 6
        i32.load
        local.set 8
        local.get 7
        i64.load
        local.set 9
        local.get 8
        local.get 9
        i32.wrap_i64
        call $__ngs_print_str
        local.get 10
        global.set $heap
        return
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

(func $type_size (param i32) (result i32) (local i32 i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64 i64) (local i32 i32 i32) (local i64)
  global.get $heap
  local.set 55
  loop $top
    block $next
      local.get 56
      i32.eqz
      if
        ;; block entry (pc=0)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 1
        local.get 1
        local.get 0
        i32.store
        local.get 1
        i32.load
        local.set 2
        i64.const 0
        local.set 3
        local.get 2
        local.get 3
        i32.wrap_i64
        i32.eq
        local.set 4
        local.get 4
        if
          i32.const 1
          local.set 56
        else
          i32.const 2
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 1
      i32.eq
      if
        ;; block if.then0 (pc=1)
        i64.const 1
        local.set 5
        local.get 5
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 2
      i32.eq
      if
        ;; block if.else1 (pc=2)
        i32.const 3
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 3
      i32.eq
      if
        ;; block if.end2 (pc=3)
        local.get 1
        i32.load
        local.set 6
        i64.const 1
        local.set 7
        local.get 6
        local.get 7
        i32.wrap_i64
        i32.eq
        local.set 8
        local.get 8
        if
          i32.const 4
          local.set 56
        else
          i32.const 5
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 4
      i32.eq
      if
        ;; block if.then3 (pc=4)
        i64.const 2
        local.set 9
        local.get 9
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 5
      i32.eq
      if
        ;; block if.else4 (pc=5)
        i32.const 6
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 6
      i32.eq
      if
        ;; block if.end5 (pc=6)
        local.get 1
        i32.load
        local.set 10
        i64.const 2
        local.set 11
        local.get 10
        local.get 11
        i32.wrap_i64
        i32.eq
        local.set 12
        local.get 12
        if
          i32.const 7
          local.set 56
        else
          i32.const 8
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 7
      i32.eq
      if
        ;; block if.then6 (pc=7)
        i64.const 4
        local.set 13
        local.get 13
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 8
      i32.eq
      if
        ;; block if.else7 (pc=8)
        i32.const 9
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 9
      i32.eq
      if
        ;; block if.end8 (pc=9)
        local.get 1
        i32.load
        local.set 14
        i64.const 3
        local.set 15
        local.get 14
        local.get 15
        i32.wrap_i64
        i32.eq
        local.set 16
        local.get 16
        if
          i32.const 10
          local.set 56
        else
          i32.const 11
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 10
      i32.eq
      if
        ;; block if.then9 (pc=10)
        i64.const 8
        local.set 17
        local.get 17
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 11
      i32.eq
      if
        ;; block if.else10 (pc=11)
        i32.const 12
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 12
      i32.eq
      if
        ;; block if.end11 (pc=12)
        local.get 1
        i32.load
        local.set 18
        i64.const 4
        local.set 19
        local.get 18
        local.get 19
        i32.wrap_i64
        i32.eq
        local.set 20
        local.get 20
        if
          i32.const 13
          local.set 56
        else
          i32.const 14
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 13
      i32.eq
      if
        ;; block if.then12 (pc=13)
        i64.const 1
        local.set 21
        local.get 21
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 14
      i32.eq
      if
        ;; block if.else13 (pc=14)
        i32.const 15
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 15
      i32.eq
      if
        ;; block if.end14 (pc=15)
        local.get 1
        i32.load
        local.set 22
        i64.const 5
        local.set 23
        local.get 22
        local.get 23
        i32.wrap_i64
        i32.eq
        local.set 24
        local.get 24
        if
          i32.const 16
          local.set 56
        else
          i32.const 17
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 16
      i32.eq
      if
        ;; block if.then15 (pc=16)
        i64.const 2
        local.set 25
        local.get 25
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 17
      i32.eq
      if
        ;; block if.else16 (pc=17)
        i32.const 18
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 18
      i32.eq
      if
        ;; block if.end17 (pc=18)
        local.get 1
        i32.load
        local.set 26
        i64.const 6
        local.set 27
        local.get 26
        local.get 27
        i32.wrap_i64
        i32.eq
        local.set 28
        local.get 28
        if
          i32.const 19
          local.set 56
        else
          i32.const 20
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 19
      i32.eq
      if
        ;; block if.then18 (pc=19)
        i64.const 4
        local.set 29
        local.get 29
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 20
      i32.eq
      if
        ;; block if.else19 (pc=20)
        i32.const 21
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 21
      i32.eq
      if
        ;; block if.end20 (pc=21)
        local.get 1
        i32.load
        local.set 30
        i64.const 7
        local.set 31
        local.get 30
        local.get 31
        i32.wrap_i64
        i32.eq
        local.set 32
        local.get 32
        if
          i32.const 22
          local.set 56
        else
          i32.const 23
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 22
      i32.eq
      if
        ;; block if.then21 (pc=22)
        i64.const 8
        local.set 33
        local.get 33
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 23
      i32.eq
      if
        ;; block if.else22 (pc=23)
        i32.const 24
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 24
      i32.eq
      if
        ;; block if.end23 (pc=24)
        local.get 1
        i32.load
        local.set 34
        i64.const 8
        local.set 35
        local.get 34
        local.get 35
        i32.wrap_i64
        i32.eq
        local.set 36
        local.get 36
        if
          i32.const 25
          local.set 56
        else
          i32.const 26
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 25
      i32.eq
      if
        ;; block if.then24 (pc=25)
        i64.const 4
        local.set 37
        local.get 37
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 26
      i32.eq
      if
        ;; block if.else25 (pc=26)
        i32.const 27
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 27
      i32.eq
      if
        ;; block if.end26 (pc=27)
        local.get 1
        i32.load
        local.set 38
        i64.const 9
        local.set 39
        local.get 38
        local.get 39
        i32.wrap_i64
        i32.eq
        local.set 40
        local.get 40
        if
          i32.const 28
          local.set 56
        else
          i32.const 29
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 28
      i32.eq
      if
        ;; block if.then27 (pc=28)
        i64.const 8
        local.set 41
        local.get 41
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 29
      i32.eq
      if
        ;; block if.else28 (pc=29)
        i32.const 30
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 30
      i32.eq
      if
        ;; block if.end29 (pc=30)
        local.get 1
        i32.load
        local.set 42
        i64.const 10
        local.set 43
        local.get 42
        local.get 43
        i32.wrap_i64
        i32.eq
        local.set 44
        local.get 44
        if
          i32.const 31
          local.set 56
        else
          i32.const 32
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 31
      i32.eq
      if
        ;; block if.then30 (pc=31)
        i64.const 1
        local.set 45
        local.get 45
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 32
      i32.eq
      if
        ;; block if.else31 (pc=32)
        i32.const 33
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 33
      i32.eq
      if
        ;; block if.end32 (pc=33)
        local.get 1
        i32.load
        local.set 46
        i64.const 11
        local.set 47
        local.get 46
        local.get 47
        i32.wrap_i64
        i32.eq
        local.set 48
        local.get 48
        if
          i32.const 34
          local.set 56
        else
          i32.const 35
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 34
      i32.eq
      if
        ;; block if.then33 (pc=34)
        i64.const 16
        local.set 49
        local.get 49
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 35
      i32.eq
      if
        ;; block if.else34 (pc=35)
        i32.const 36
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 36
      i32.eq
      if
        ;; block if.end35 (pc=36)
        local.get 1
        i32.load
        local.set 50
        i64.const 12
        local.set 51
        local.get 50
        local.get 51
        i32.wrap_i64
        i32.eq
        local.set 52
        local.get 52
        if
          i32.const 37
          local.set 56
        else
          i32.const 38
          local.set 56
        end
        br 1 ;; $next
      end
      local.get 56
      i32.const 37
      i32.eq
      if
        ;; block if.then36 (pc=37)
        i64.const 8
        local.set 53
        local.get 53
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      local.get 56
      i32.const 38
      i32.eq
      if
        ;; block if.else37 (pc=38)
        i32.const 39
        local.set 56
        br 1 ;; $next
      end
      local.get 56
      i32.const 39
      i32.eq
      if
        ;; block if.end38 (pc=39)
        i64.const 0
        local.set 54
        local.get 54
        i32.wrap_i64
        local.get 55
        global.set $heap
        return
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

(func $is_prime (param i32) (result i32) (local i32 i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32) (local i64 i64) (local i32 i32 i32 i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32 i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32 i32 i32 i32 i32 i32) (local i64 i64) (local i32 i32 i32) (local i64)
  global.get $heap
  local.set 45
  loop $top
    block $next
      local.get 46
      i32.eqz
      if
        ;; block entry (pc=0)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 1
        local.get 1
        local.get 0
        i32.store
        local.get 1
        i32.load
        local.set 2
        i64.const 2
        local.set 3
        local.get 2
        local.get 3
        i32.wrap_i64
        i32.lt_s
        local.set 4
        local.get 4
        if
          i32.const 1
          local.set 46
        else
          i32.const 2
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 1
      i32.eq
      if
        ;; block if.then0 (pc=1)
        i64.const 0
        local.set 5
        local.get 5
        i32.wrap_i64
        local.get 45
        global.set $heap
        return
      end
      local.get 46
      i32.const 2
      i32.eq
      if
        ;; block if.else1 (pc=2)
        i32.const 3
        local.set 46
        br 1 ;; $next
      end
      local.get 46
      i32.const 3
      i32.eq
      if
        ;; block if.end2 (pc=3)
        local.get 1
        i32.load
        local.set 6
        i64.const 2
        local.set 7
        local.get 6
        local.get 7
        i32.wrap_i64
        i32.eq
        local.set 8
        local.get 8
        if
          i32.const 4
          local.set 46
        else
          i32.const 5
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 4
      i32.eq
      if
        ;; block if.then3 (pc=4)
        i64.const 1
        local.set 9
        local.get 9
        i32.wrap_i64
        local.get 45
        global.set $heap
        return
      end
      local.get 46
      i32.const 5
      i32.eq
      if
        ;; block if.else4 (pc=5)
        i32.const 6
        local.set 46
        br 1 ;; $next
      end
      local.get 46
      i32.const 6
      i32.eq
      if
        ;; block if.end5 (pc=6)
        local.get 1
        i32.load
        local.set 10
        i64.const 2
        local.set 11
        local.get 10
        local.get 11
        i32.wrap_i64
        i32.rem_s
        local.set 12
        i64.const 0
        local.set 13
        local.get 12
        local.get 13
        i32.wrap_i64
        i32.eq
        local.set 14
        local.get 14
        if
          i32.const 7
          local.set 46
        else
          i32.const 8
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 7
      i32.eq
      if
        ;; block if.then6 (pc=7)
        i64.const 0
        local.set 15
        local.get 15
        i32.wrap_i64
        local.get 45
        global.set $heap
        return
      end
      local.get 46
      i32.const 8
      i32.eq
      if
        ;; block if.else7 (pc=8)
        i32.const 9
        local.set 46
        br 1 ;; $next
      end
      local.get 46
      i32.const 9
      i32.eq
      if
        ;; block if.end8 (pc=9)
        i64.const 3
        local.set 16
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 17
        local.get 17
        local.get 16
        i32.wrap_i64
        i32.store
        i32.const 10
        local.set 46
        br 1 ;; $next
      end
      local.get 46
      i32.const 10
      i32.eq
      if
        ;; block while.cond9 (pc=10)
        local.get 17
        i32.load
        local.set 18
        local.get 17
        i32.load
        local.set 19
        local.get 18
        i64.extend_i32_s
        local.get 19
        i64.extend_i32_s
        i64.mul
        local.set 48
        local.get 48
        i64.const 32
        i64.shl
        i64.const 32
        i64.shr_s
        local.get 48
        i64.ne
        local.set 21
        local.get 48
        i32.wrap_i64
        local.set 20
        local.get 21
        if
          i32.const 13
          local.set 46
        else
          i32.const 14
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 11
      i32.eq
      if
        ;; block while.body10 (pc=11)
        local.get 1
        i32.load
        local.set 29
        local.get 17
        i32.load
        local.set 30
        local.get 29
        local.get 30
        i32.rem_s
        local.set 31
        i64.const 0
        local.set 32
        local.get 31
        local.get 32
        i32.wrap_i64
        i32.eq
        local.set 33
        local.get 33
        if
          i32.const 15
          local.set 46
        else
          i32.const 16
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 12
      i32.eq
      if
        ;; block while.end11 (pc=12)
        i64.const 1
        local.set 44
        local.get 44
        i32.wrap_i64
        local.get 45
        global.set $heap
        return
      end
      local.get 46
      i32.const 13
      i32.eq
      if
        ;; block of.fail12 (pc=13)
        i32.const 112
        local.set 22
        local.get 22
        i32.const 0
        i32.add
        local.set 23
        local.get 22
        i32.const 8
        i32.add
        local.set 24
        local.get 23
        i32.load
        local.set 25
        local.get 24
        i64.load
        local.set 26
        local.get 25
        local.get 26
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 46
      i32.const 14
      i32.eq
      if
        ;; block of.ok13 (pc=14)
        local.get 1
        i32.load
        local.set 27
        local.get 20
        local.get 27
        i32.le_s
        local.set 28
        local.get 28
        if
          i32.const 11
          local.set 46
        else
          i32.const 12
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 15
      i32.eq
      if
        ;; block if.then14 (pc=15)
        i64.const 0
        local.set 34
        local.get 34
        i32.wrap_i64
        local.get 45
        global.set $heap
        return
      end
      local.get 46
      i32.const 16
      i32.eq
      if
        ;; block if.else15 (pc=16)
        i32.const 17
        local.set 46
        br 1 ;; $next
      end
      local.get 46
      i32.const 17
      i32.eq
      if
        ;; block if.end16 (pc=17)
        local.get 17
        i32.load
        local.set 35
        i64.const 2
        local.set 36
        local.get 35
        local.get 36
        i32.wrap_i64
        i32.add
        local.set 37
        local.get 35
        local.get 37
        i32.xor
        local.get 36
        i32.wrap_i64
        local.get 37
        i32.xor
        i32.and
        i32.const 0
        i32.lt_s
        local.set 38
        local.get 38
        if
          i32.const 18
          local.set 46
        else
          i32.const 19
          local.set 46
        end
        br 1 ;; $next
      end
      local.get 46
      i32.const 18
      i32.eq
      if
        ;; block of.fail17 (pc=18)
        i32.const 144
        local.set 39
        local.get 39
        i32.const 0
        i32.add
        local.set 40
        local.get 39
        i32.const 8
        i32.add
        local.set 41
        local.get 40
        i32.load
        local.set 42
        local.get 41
        i64.load
        local.set 43
        local.get 42
        local.get 43
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 46
      i32.const 19
      i32.eq
      if
        ;; block of.ok18 (pc=19)
        local.get 17
        local.get 37
        i32.store
        i32.const 10
        local.set 46
        br 1 ;; $next
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

(func $gcd (param i32) (param i32) (result i32) (local i32 i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (local i64)
  global.get $heap
  local.set 18
  loop $top
    block $next
      local.get 19
      i32.eqz
      if
        ;; block entry (pc=0)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 2
        local.get 2
        local.get 0
        i32.store
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 3
        local.get 3
        local.get 1
        i32.store
        local.get 2
        i32.load
        local.set 4
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 5
        local.get 5
        local.get 4
        i32.store
        local.get 3
        i32.load
        local.set 6
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 7
        local.get 7
        local.get 6
        i32.store
        i32.const 1
        local.set 19
        br 1 ;; $next
      end
      local.get 19
      i32.const 1
      i32.eq
      if
        ;; block while.cond0 (pc=1)
        local.get 7
        i32.load
        local.set 8
        i64.const 0
        local.set 9
        local.get 8
        local.get 9
        i32.wrap_i64
        i32.ne
        local.set 10
        local.get 10
        if
          i32.const 2
          local.set 19
        else
          i32.const 3
          local.set 19
        end
        br 1 ;; $next
      end
      local.get 19
      i32.const 2
      i32.eq
      if
        ;; block while.body1 (pc=2)
        local.get 7
        i32.load
        local.set 11
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 12
        local.get 12
        local.get 11
        i32.store
        local.get 5
        i32.load
        local.set 13
        local.get 7
        i32.load
        local.set 14
        local.get 13
        local.get 14
        i32.rem_s
        local.set 15
        local.get 7
        local.get 15
        i32.store
        local.get 12
        i32.load
        local.set 16
        local.get 5
        local.get 16
        i32.store
        i32.const 1
        local.set 19
        br 1 ;; $next
      end
      local.get 19
      i32.const 3
      i32.eq
      if
        ;; block while.end2 (pc=3)
        local.get 5
        i32.load
        local.set 17
        local.get 17
        local.get 18
        global.set $heap
        return
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

(func $factorial (param i32) (result i32) (local i32 i32) (local i64) (local i32) (local i64) (local i32 i32) (local i64) (local i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32) (local i64)
  global.get $heap
  local.set 24
  loop $top
    block $next
      local.get 25
      i32.eqz
      if
        ;; block entry (pc=0)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 1
        local.get 1
        local.get 0
        i32.store
        local.get 1
        i32.load
        local.set 2
        i64.const 1
        local.set 3
        local.get 2
        local.get 3
        i32.wrap_i64
        i32.le_s
        local.set 4
        local.get 4
        if
          i32.const 1
          local.set 25
        else
          i32.const 2
          local.set 25
        end
        br 1 ;; $next
      end
      local.get 25
      i32.const 1
      i32.eq
      if
        ;; block if.then0 (pc=1)
        i64.const 1
        local.set 5
        local.get 5
        i32.wrap_i64
        local.get 24
        global.set $heap
        return
      end
      local.get 25
      i32.const 2
      i32.eq
      if
        ;; block if.else1 (pc=2)
        i32.const 3
        local.set 25
        br 1 ;; $next
      end
      local.get 25
      i32.const 3
      i32.eq
      if
        ;; block if.end2 (pc=3)
        local.get 1
        i32.load
        local.set 6
        local.get 1
        i32.load
        local.set 7
        i64.const 1
        local.set 8
        local.get 7
        local.get 8
        i32.wrap_i64
        i32.sub
        local.set 9
        local.get 7
        local.get 8
        i32.wrap_i64
        i32.xor
        local.get 7
        local.get 9
        i32.xor
        i32.and
        i32.const 0
        i32.lt_s
        local.set 10
        local.get 10
        if
          i32.const 4
          local.set 25
        else
          i32.const 5
          local.set 25
        end
        br 1 ;; $next
      end
      local.get 25
      i32.const 4
      i32.eq
      if
        ;; block of.fail3 (pc=4)
        i32.const 176
        local.set 11
        local.get 11
        i32.const 0
        i32.add
        local.set 12
        local.get 11
        i32.const 8
        i32.add
        local.set 13
        local.get 12
        i32.load
        local.set 14
        local.get 13
        i64.load
        local.set 15
        local.get 14
        local.get 15
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 25
      i32.const 5
      i32.eq
      if
        ;; block of.ok4 (pc=5)
        local.get 9
        call $factorial
        local.set 16
        local.get 6
        i64.extend_i32_s
        local.get 16
        i64.extend_i32_s
        i64.mul
        local.set 27
        local.get 27
        i64.const 32
        i64.shl
        i64.const 32
        i64.shr_s
        local.get 27
        i64.ne
        local.set 18
        local.get 27
        i32.wrap_i64
        local.set 17
        local.get 18
        if
          i32.const 6
          local.set 25
        else
          i32.const 7
          local.set 25
        end
        br 1 ;; $next
      end
      local.get 25
      i32.const 6
      i32.eq
      if
        ;; block of.fail5 (pc=6)
        i32.const 208
        local.set 19
        local.get 19
        i32.const 0
        i32.add
        local.set 20
        local.get 19
        i32.const 8
        i32.add
        local.set 21
        local.get 20
        i32.load
        local.set 22
        local.get 21
        i64.load
        local.set 23
        local.get 22
        local.get 23
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 25
      i32.const 7
      i32.eq
      if
        ;; block of.ok6 (pc=7)
        local.get 17
        local.get 24
        global.set $heap
        return
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

(func $fibonacci (param i32) (result i32) (local i32 i32) (local i64) (local i32 i32) (local i64) (local i32) (local i64) (local i32) (local i64) (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32 i32 i32) (local i64) (local i32 i32 i32 i32) (local i64)
  global.get $heap
  local.set 37
  loop $top
    block $next
      local.get 38
      i32.eqz
      if
        ;; block entry (pc=0)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 1
        local.get 1
        local.get 0
        i32.store
        local.get 1
        i32.load
        local.set 2
        i64.const 1
        local.set 3
        local.get 2
        local.get 3
        i32.wrap_i64
        i32.le_s
        local.set 4
        local.get 4
        if
          i32.const 1
          local.set 38
        else
          i32.const 2
          local.set 38
        end
        br 1 ;; $next
      end
      local.get 38
      i32.const 1
      i32.eq
      if
        ;; block if.then0 (pc=1)
        local.get 1
        i32.load
        local.set 5
        local.get 5
        local.get 37
        global.set $heap
        return
      end
      local.get 38
      i32.const 2
      i32.eq
      if
        ;; block if.else1 (pc=2)
        i32.const 3
        local.set 38
        br 1 ;; $next
      end
      local.get 38
      i32.const 3
      i32.eq
      if
        ;; block if.end2 (pc=3)
        i64.const 0
        local.set 6
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 7
        local.get 7
        local.get 6
        i32.wrap_i64
        i32.store
        i64.const 1
        local.set 8
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 9
        local.get 9
        local.get 8
        i32.wrap_i64
        i32.store
        i64.const 2
        local.set 10
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 11
        local.get 11
        local.get 10
        i32.wrap_i64
        i32.store
        i32.const 4
        local.set 38
        br 1 ;; $next
      end
      local.get 38
      i32.const 4
      i32.eq
      if
        ;; block while.cond3 (pc=4)
        local.get 11
        i32.load
        local.set 12
        local.get 1
        i32.load
        local.set 13
        local.get 12
        local.get 13
        i32.le_s
        local.set 14
        local.get 14
        if
          i32.const 5
          local.set 38
        else
          i32.const 6
          local.set 38
        end
        br 1 ;; $next
      end
      local.get 38
      i32.const 5
      i32.eq
      if
        ;; block while.body4 (pc=5)
        local.get 7
        i32.load
        local.set 15
        local.get 9
        i32.load
        local.set 16
        local.get 15
        local.get 16
        i32.add
        local.set 17
        local.get 15
        local.get 17
        i32.xor
        local.get 16
        local.get 17
        i32.xor
        i32.and
        i32.const 0
        i32.lt_s
        local.set 18
        local.get 18
        if
          i32.const 7
          local.set 38
        else
          i32.const 8
          local.set 38
        end
        br 1 ;; $next
      end
      local.get 38
      i32.const 6
      i32.eq
      if
        ;; block while.end5 (pc=6)
        local.get 9
        i32.load
        local.set 36
        local.get 36
        local.get 37
        global.set $heap
        return
      end
      local.get 38
      i32.const 7
      i32.eq
      if
        ;; block of.fail6 (pc=7)
        i32.const 240
        local.set 19
        local.get 19
        i32.const 0
        i32.add
        local.set 20
        local.get 19
        i32.const 8
        i32.add
        local.set 21
        local.get 20
        i32.load
        local.set 22
        local.get 21
        i64.load
        local.set 23
        local.get 22
        local.get 23
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 38
      i32.const 8
      i32.eq
      if
        ;; block of.ok7 (pc=8)
        global.get $heap
        global.get $heap
        i32.const 16
        i32.add
        global.set $heap
        local.set 24
        local.get 24
        local.get 17
        i32.store
        local.get 9
        i32.load
        local.set 25
        local.get 7
        local.get 25
        i32.store
        local.get 24
        i32.load
        local.set 26
        local.get 9
        local.get 26
        i32.store
        local.get 11
        i32.load
        local.set 27
        i64.const 1
        local.set 28
        local.get 27
        local.get 28
        i32.wrap_i64
        i32.add
        local.set 29
        local.get 27
        local.get 29
        i32.xor
        local.get 28
        i32.wrap_i64
        local.get 29
        i32.xor
        i32.and
        i32.const 0
        i32.lt_s
        local.set 30
        local.get 30
        if
          i32.const 9
          local.set 38
        else
          i32.const 10
          local.set 38
        end
        br 1 ;; $next
      end
      local.get 38
      i32.const 9
      i32.eq
      if
        ;; block of.fail8 (pc=9)
        i32.const 272
        local.set 31
        local.get 31
        i32.const 0
        i32.add
        local.set 32
        local.get 31
        i32.const 8
        i32.add
        local.set 33
        local.get 32
        i32.load
        local.set 34
        local.get 33
        i64.load
        local.set 35
        local.get 34
        local.get 35
        i32.wrap_i64
        call $__ngs_panic
        unreachable
      end
      local.get 38
      i32.const 10
      i32.eq
      if
        ;; block of.ok9 (pc=10)
        local.get 11
        local.get 29
        i32.store
        i32.const 4
        local.set 38
        br 1 ;; $next
      end
      ;; 不正な pc は到達不能
      unreachable
    end ;; $next
    br 0 ;; $top
  end ;; $top
  unreachable ;; ループは必ず return で抜ける
  ) ;; func

  (export "type_size" (func $type_size))
  (export "is_prime" (func $is_prime))
  (export "gcd" (func $gcd))
  (export "factorial" (func $factorial))
  (export "fibonacci" (func $fibonacci))
  (export "main" (func $main))
)
