// generated by nagiscript (NGS-IR exports -> TypeScript)
// Strings cross the boundary as { ptr: number, len: number } views into the exported `memory`.

export function type_size(kind: number): number;
export function is_prime(n: number): number;
export function gcd(a: number, b: number): number;
export function factorial(n: number): number;
export function fibonacci(n: number): number;
